"""empty message

Revision ID: 0aae2a4317d8
Revises: 561447ff1e90
Create Date: 2021-09-27 20:09:19.925673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0aae2a4317d8'
down_revision = '561447ff1e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('status', mysql.ENUM('第一轮面试', '第二轮面试', '第三轮面试', '通过', '未通过', '未审核'), server_default=sa.text("'未审核'"), nullable=True))
    # ### end Alembic commands ###
