"""empty message

Revision ID: 57b92c12dfd0
Revises: 
Create Date: 2021-09-25 12:06:23.293977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b92c12dfd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('uniLearn', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('interview_time', sa.DATE(), nullable=True),
    sa.Column('status', sa.Enum('第一轮面试', '第二轮面试', '第三轮面试', '通过', '未通过'), server_default='第一轮面试', nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('campus', sa.Enum('河西校区', '泰达校区'), server_default='泰达校区', nullable=True),
    sa.Column('tel', sa.String(length=12), nullable=True),
    sa.Column('introduce', sa.String(length=1000), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('academy', sa.String(length=100), nullable=True),
    sa.Column('annotation', sa.String(length=10000), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('tutor',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('salt', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('campus', sa.Enum('河西校区', '泰达校区'), server_default='泰达校区', nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('qq', sa.String(length=20), nullable=True),
    sa.Column('roleType', sa.Enum('tutor', 'leader'), server_default='tutor', nullable=True),
    sa.Column('status', sa.Enum('已审核', '未审核'), server_default='未审核', nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('association',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.uid'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.uid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('tutor')
    op.drop_table('student')
    op.drop_table('group')
    # ### end Alembic commands ###
