"""empty message

Revision ID: 6a1728b9ba95
Revises: ea72f02da3ea
Create Date: 2021-09-25 12:41:33.041152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1728b9ba95'
down_revision = 'ea72f02da3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('email_status', sa.Enum('已发送', '未发送'), server_default='未发送', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'email_status')
    # ### end Alembic commands ###
