"""empty message

Revision ID: ea72f02da3ea
Revises: e719bd50d07e
Create Date: 2021-09-25 12:37:28.109655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea72f02da3ea'
down_revision = 'e719bd50d07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('status', sa.Enum('第一轮面试', '第二轮面试', '第三轮面试', '通过', '未通过', '未审核'), server_default='未审核', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'status')
    # ### end Alembic commands ###
