"""empty message

Revision ID: 32f658456655
Revises: 6a1728b9ba95
Create Date: 2021-09-25 13:28:29.871577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f658456655'
down_revision = '6a1728b9ba95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'rate')
    # ### end Alembic commands ###
