"""empty message

Revision ID: 9ace33f47d6f
Revises: 0aae2a4317d8
Create Date: 2021-09-27 20:09:39.851309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ace33f47d6f'
down_revision = '0aae2a4317d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('status', sa.Enum('第一轮面试', '第二轮面试', '第三轮面试', '通过', '不通过', '未审核'), server_default='未审核', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'status')
    # ### end Alembic commands ###
