"""empty message

Revision ID: e719bd50d07e
Revises: 57b92c12dfd0
Create Date: 2021-09-25 12:37:17.056128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e719bd50d07e'
down_revision = '57b92c12dfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('status', mysql.ENUM('第一轮面试', '第二轮面试', '第三轮面试', '通过', '未通过'), server_default=sa.text("'第一轮面试'"), nullable=True))
    # ### end Alembic commands ###
